<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GeoSphere.Application\GeoSphere.Application.csproj" />
    <ProjectReference Include="..\GeoSphere.Domain\GeoSphere.Domain.csproj" />
  </ItemGroup>

</Project>
